defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: true
  username: root
  password:

development:
  <<: *defaults
  pool: 360
  checkout_timeout: 720
  database: shoes_development

test:
  <<: *defaults
  database: shoes_test
