development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 360
  checkout_timeout: 720
  database: shoes_development
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: shoes_test
  username: root
  password:

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 360
  checkout_timeout: 720
  database: shoes_staging
  username: shoes
  password: 4g6RmHezzqu

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 360
  checkout_timeout: 720
  database: shoes_production
  username: shoes
  password: n8gHbrNanrUXajF2ea