---
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - carmensteffens
  - corello
  - louloux
  - melissa
  - miezko
  - schutz
  - [default, 2]
development:
  :concurrency: 20
staging:
  :concurrency: 30
production:
  :concurrency: 60