defaults: &defaults
  auth:
    name: fucking
    password: Amazing2312
  email:
    address: 'smtp.gmail.com',
    authentication: 'plain',
    domain: buscasapato.com.br
    enable_starttls_auto: true
    user_name: contato@buscasapato.com.br
    password: xsbi3JHnK9mTo
    port: 587,

production:
  <<: *defaults
  crawler_threads: 10
  domain: buscasapato.com.br
  host: http://buscasapato.com.br